/**
 * The drift gate.
 *
 * Committed fixtures are only trustworthy while they still describe the config
 * and the Solidity they were generated for. `check` re-derives the schema hash
 * from the config and compares it against every fixture and against the
 * generated library, without running quint at all, so it is cheap enough to sit
 * in the same CI job as everything else.
 */

import fs from 'node:fs';
import path from 'node:path';

import { TOOL_VERSION } from './gen.mjs';

const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const posix = (p) => p.split(path.sep).join('/');

/** Older fixtures carry no `actionCounts`; a floor cannot be checked against them. */
function hasActionCounts(fixtures, fixtureDir) {
  const first = JSON.parse(fs.readFileSync(path.join(fixtureDir, fixtures[0]), 'utf8'));
  return Boolean(first.meta?.actionCounts);
}

export function checkModel(model, root) {
  const problems = [];
  const fixtureDir = path.resolve(root, model.fixtureOut, model.name);

  if (!fs.existsSync(fixtureDir)) {
    problems.push(`no fixtures at ${path.relative(root, fixtureDir)} - run \`quint-sol-connect gen ${model.name}\``);
    return { problems, fixtures: 0 };
  }

  const fixtures = fs
    .readdirSync(fixtureDir)
    .filter((f) => f.endsWith('.json') && !f.endsWith('.itf.json'))
    .sort();

  if (fixtures.length === 0) {
    problems.push(`${path.relative(root, fixtureDir)} holds no trace fixtures`);
  }

  // Every fixture in a directory was generated together, so a shape or version
  // change hits all of them at once. Reported once with a count, rather than
  // once per file, so the actual problem is not buried in its own repetition.
  const schemaDrift = [];
  const versionDrift = new Map();
  const observed = new Map();

  for (const f of fixtures) {
    const abs = path.join(fixtureDir, f);
    let fixture;
    try {
      fixture = JSON.parse(fs.readFileSync(abs, 'utf8'));
    } catch (e) {
      problems.push(`${f}: not valid JSON (${e.message})`);
      continue;
    }
    const meta = fixture.meta ?? {};

    for (const [action, n] of Object.entries(meta.actionCounts ?? {})) {
      observed.set(action, (observed.get(action) ?? 0) + n);
    }

    if (meta.schemaHash !== model.schemaHash) schemaDrift.push(f);
    if (meta.toolVersion !== TOOL_VERSION) {
      versionDrift.set(meta.toolVersion, (versionDrift.get(meta.toolVersion) ?? 0) + 1);
    }
    if (meta.spec !== model.specPath) {
      problems.push(`${f}: generated from ${meta.spec}, config now says ${model.specPath}`);
    }
    if (typeof fixture.steps !== 'string' || !fixture.steps.startsWith('0x')) {
      problems.push(`${f}: "steps" is not a hex blob`);
    }
    const itf = path.resolve(root, meta.itf ?? '');
    if (!meta.itf || !fs.existsSync(itf)) {
      problems.push(`${f}: its ITF companion (${meta.itf}) is missing`);
    }
  }

  if (schemaDrift.length) {
    problems.push(
      `${schemaDrift.length} of ${fixtures.length} fixtures carry schema hash ` +
        `${JSON.parse(fs.readFileSync(path.join(fixtureDir, schemaDrift[0]), 'utf8')).meta.schemaHash}, ` +
        `but the config now yields ${model.schemaHash}. The state or action shape changed.`,
    );
  }
  for (const [version, n] of versionDrift) {
    problems.push(
      `${n} fixture(s) were generated by quint-sol-connect ${version}, this is ${TOOL_VERSION}. ` +
        'The tool was bumped without regenerating.',
    );
  }

  // Coverage floors. An action can go from 40 steps to 1 without any test
  // failing - the traces still replay, they just stop exercising it. Declaring
  // a floor turns that silent decay into a failure, which is the same class of
  // problem as a handler that reverts on every call.
  const floors = model.coverage?.minSteps ?? {};
  if (Object.keys(floors).length) {
    const known = new Set(model.actions.map((a) => a.name));
    for (const action of Object.keys(floors)) {
      if (!known.has(action)) {
        problems.push(`coverage.minSteps names "${action}", which is not one of this spec's actions`);
      }
    }

    // `actionCounts` is optional metadata. Without it the floors cannot be
    // evaluated at all - and reporting every action as "ran 0 times" would say
    // something false, when the truth is that nothing was measured.
    if (fixtures.length && !hasActionCounts(fixtures, fixtureDir)) {
      problems.push(
        'coverage floors are declared but the fixtures carry no per-action counts - regenerate',
      );
    } else {
      for (const [action, min] of Object.entries(floors)) {
        if (!known.has(action)) continue;
        const got = observed.get(action) ?? 0;
        if (got < min) {
          problems.push(
            `coverage: \`${action}\` ran ${got} time(s) across the committed traces, floor is ${min}. ` +
              "Raise traces/maxSteps, widen the action's guard, or lower the floor deliberately.",
          );
        }
      }
    }
  }

  // The generated library carries the same hash; if it does not, the Solidity
  // in the tree was generated from a different config than the fixtures were.
  const libFile = path.resolve(root, model.solidityOut, `${model.lib}.sol`);
  if (!fs.existsSync(libFile)) {
    problems.push(`${path.relative(root, libFile)} is missing - run \`quint-sol-connect gen ${model.name}\``);
  } else {
    const src = fs.readFileSync(libFile, 'utf8');
    const m = /SCHEMA_HASH\s*=\s*(0x[0-9a-fA-F]{64});/.exec(src);
    if (!m) problems.push(`${path.relative(root, libFile)}: no SCHEMA_HASH found`);
    else if (m[1].toLowerCase() !== model.schemaHash.toLowerCase()) {
      problems.push(
        `${path.relative(root, libFile)}: SCHEMA_HASH ${m[1]} but the config yields ${model.schemaHash}`,
      );
    }
  }

  const replayFile = path.resolve(root, model.solidityOut, `${cap(model.name)}SpecReplay.sol`);
  if (!fs.existsSync(replayFile)) problems.push(`${path.relative(root, replayFile)} is missing`);

  // The generated tests name their fixtures as literal paths, and `vm.readFile`
  // is the first thing a replay does. A fixture that was deleted or renamed by
  // hand therefore fails inside `forge test`, one test at a time, with a file
  // error rather than a drift error. Cheaper to say it here.
  const tracesFile = path.resolve(root, model.solidityOut, `${cap(model.name)}Traces.t.sol`);
  if (!fs.existsSync(tracesFile)) {
    problems.push(`${path.relative(root, tracesFile)} is missing`);
  } else {
    const src = fs.readFileSync(tracesFile, 'utf8');
    const replayed = [...src.matchAll(/_replay\("([^"]+)"\)/g)].map((m) => m[1]);
    const relDir = posix(path.relative(root, fixtureDir));
    const expected = fixtures.map((f) => `${relDir}/${f}`);

    const missing = replayed.filter((p) => !fs.existsSync(path.resolve(root, p)));
    if (missing.length) {
      problems.push(
        `${path.relative(root, tracesFile)} replays ${missing.length} fixture(s) that do not ` +
          `exist: ${missing.join(', ')}`,
      );
    }
    const orphaned = expected.filter((p) => !replayed.includes(p));
    if (orphaned.length) {
      problems.push(
        `${orphaned.length} fixture(s) have no test in ${path.relative(root, tracesFile)}: ` +
          `${orphaned.join(', ')}`,
      );
    }
  }

  return { problems, fixtures: fixtures.length };
}
