/**
 * Solidity emission: three files per spec.
 *
 *   <Lib>.sol            types + schema hash + name helpers
 *   <Name>SpecReplay.sol the replay loop and the per-field comparisons
 *   <Name>Traces.t.sol   one Foundry test per committed trace
 *
 * The split exists so the hand-written driver sits *between* two generated
 * layers: it inherits the replay loop and is inherited by the test contract.
 * That is what lets Foundry run one test per trace, which in turn is what makes
 * a failure name a single trace you can rerun on its own.
 */

const HEADER = (model, cmd) =>
  `// SPDX-License-Identifier: Apache-2.0\n` +
  `pragma solidity ${model.pragma};\n\n` +
  `// GENERATED by @lelantos-org/quint-sol-connect from ${model.specPath}\n` +
  `// Do not edit. Regenerate with \`${cmd}\`.\n`;

const lower1 = (s) => s.charAt(0).toLowerCase() + s.slice(1);
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const sanitize = (s) => s.replace(/[^A-Za-z0-9]/g, '_');

/** `library <Spec>Spec` with every type the replay and the driver share. */
export function emitSpecLibrary(model, cmd) {
  // Inside the library its own members are in scope, so declarations here use
  // bare names; only references from outside get the `<Lib>.` prefix.
  const reachable = reachableDecls(model);
  const L = [];
  L.push(HEADER(model, cmd));
  L.push(`library ${model.lib} {`);
  L.push(`    /// keccak256 of the canonical ABI type string for \`Step[]\`.`);
  L.push(`    /// Asserted against every fixture's \`meta.schemaHash\` before decoding, so a`);
  L.push(`    /// config change that was not followed by a regeneration fails by name.`);
  L.push(`    bytes32 internal constant SCHEMA_HASH = ${model.schemaHash};`);
  L.push('');
  L.push(`    /// ${model.canonical}`);
  L.push(`    string internal constant CANONICAL_TYPE = "${model.canonical}";`);
  L.push('');
  L.push(`    /// Order pins the enum values; it comes from the config's \`actions\` map.`);
  L.push(`    enum Action { ${model.actions.map((a) => a.enumName).join(', ')} }`);
  L.push('');

  for (const e of model.decls.enums.values()) {
    if (!reachable.has(e.name)) continue;
    L.push(`    enum ${e.name} { ${e.variants.join(', ')} }`);
    L.push('');
  }

  for (const s of model.decls.structs.values()) {
    if (!reachable.has(s.name)) continue;
    L.push(`    struct ${s.name} {`);
    for (const f of s.fields) L.push(`        ${f.node.solType} ${f.name};`);
    L.push('    }');
    L.push('');
  }

  L.push('    /// One per Quint state variable, in config declaration order.');
  for (const [name, why] of Object.entries(model.ignoreState)) {
    L.push(`    /// Not compared: \`${name}\` - ${why}`);
  }
  L.push('    struct State {');
  for (const s of model.state) L.push(`        ${s.node.solType} ${s.name};`);
  L.push('    }');
  L.push('');

  L.push('    /// The union of every action\'s nondet picks. A step carries the whole');
  L.push('    /// struct whatever action it took, so `has*` distinguishes "not drawn');
  L.push('    /// this step" from "drawn, and the value was zero".');
  L.push('    struct Picks {');
  for (const p of model.picks) {
    L.push(`        bool has${cap(p.name)};`);
    L.push(`        ${p.node.solType} ${p.name};`);
  }
  if (model.picks.length === 0) L.push('        bool unused;');
  L.push('    }');
  L.push('');

  L.push('    struct Step {');
  L.push('        Action action;');
  L.push('        Picks picks;');
  L.push('        /// The model state *after* `action` ran.');
  L.push('        State post;');
  L.push('    }');
  L.push('');

  L.push(...nameFn('Action', 'actionName', model.actions.map((a) => ({ enumName: a.enumName, label: a.name })), model.lib));
  for (const e of model.decls.enums.values()) {
    if (!reachable.has(e.name)) continue;
    L.push('');
    L.push(...nameFn(e.name, `${lower1(e.name)}Name`, e.variants.map((v) => ({ enumName: v, label: v })), model.lib));
  }

  L.push('}');
  return L.join('\n') + '\n';
}

/**
 * Struct and enum names actually reachable from `State` or `Picks`.
 *
 * Resolving a map's value record registers a struct that the flattened entry
 * type then supersedes. Emitting it would leave dead declarations in generated
 * code, which invites someone to wonder what they are for.
 */
function reachableDecls(model) {
  const seen = new Set();
  const walk = (node) => {
    if (!node) return;
    if (node.kind === 'array') return walk(node.inner);
    if (node.kind === 'enum') {
      seen.add(node.decl.name);
      return;
    }
    if (node.kind === 'struct') {
      if (seen.has(node.decl.name)) return;
      seen.add(node.decl.name);
      for (const f of node.fields) walk(f.node);
    }
  };
  for (const s of model.state) walk(s.node);
  for (const p of model.picks) walk(p.node);
  return seen;
}

function nameFn(enumName, fnName, entries, lib) {
  const L = [];
  L.push(`    /// Names rather than indices, so a divergence reads as a value a human wrote.`);
  L.push(`    function ${fnName}(${enumName} v) internal pure returns (string memory) {`);
  entries.forEach((e, i) => {
    const last = i === entries.length - 1;
    if (last) L.push(`        return "${e.label}";`);
    else L.push(`        if (v == ${enumName}.${e.enumName}) return "${e.label}";`);
  });
  L.push('    }');
  return L;
}

/** `abstract contract <Name>SpecReplay` - the loop plus the comparisons. */
export function emitSpecReplay(model, cmd, { runtimeImport }) {
  const q = model.qualify;
  const C = `${cap(model.name)}SpecReplay`;
  const L = [];
  L.push(HEADER(model, cmd));
  L.push(`import { QuintReplayBase } from "${runtimeImport}/QuintReplayBase.sol";`);
  L.push(`import { QuintTrace } from "${runtimeImport}/QuintTrace.sol";`);
  L.push('');
  L.push(`import { ${model.lib} } from "./${model.lib}.sol";`);
  L.push('');
  L.push(`/// Replay half of the driver for ${model.specPath}.`);
  L.push('///');
  L.push('/// A concrete driver inherits this and supplies two things: `apply_`, which');
  L.push('/// drives the implementation for one model action, and `_project`, which reads');
  L.push('/// the implementation back into the model\'s vocabulary.');
  L.push(`abstract contract ${C} is QuintReplayBase {`);
  L.push('    // --- what the driver implements --------------------------------------');
  L.push('');
  L.push('    /// Drive the implementation for one model action. External so `_dispatch`');
  L.push('    /// can catch a revert and report it as an enabledness divergence; every');
  L.push('    /// implementation must reject callers other than `address(this)`.');
  L.push(`    function apply_(${model.lib}.Action action, ${model.lib}.Picks memory picks) external virtual;`);
  L.push('');
  L.push('    /// Read live implementation state into the model\'s shape.');
  L.push(`    function _project() internal view virtual returns (${model.lib}.State memory);`);
  L.push('');
  L.push('    // --- the replay loop --------------------------------------------------');
  L.push('');
  L.push('    function _replay(string memory path) internal {');
  L.push('        (QuintTrace.Meta memory meta, bytes memory blob) =');
  L.push(`            QuintTrace.load(path, ${model.lib}.SCHEMA_HASH);`);
  L.push('        _beginTrace(path, meta);');
  L.push('');
  L.push(`        ${model.lib}.Step[] memory steps = abi.decode(blob, (${model.lib}.Step[]));`);
  L.push('');
  L.push('        for (uint256 i = 0; i < steps.length; i++) {');
  L.push('            _stepIndex = i;');
  L.push('            _mismatches = 0;');
  L.push(`            ${model.lib}.Step memory s = steps[i];`);
  L.push(`            string memory name = ${model.lib}.actionName(s.action);`);
  L.push('');
  L.push('            if (quintVerbose >= 1) console2.log("  [%s] %s", vm.toString(i), name);');
  L.push('');
  L.push('            // Step 0 is the post-`init` state. There is no action to drive, only');
  L.push('            // the claim that `setUp` left the implementation where the model');
  L.push('            // starts - which is worth checking on its own.');
  L.push('            if (i != 0) {');
  L.push('                _requirePicks(s.action, s.picks);');
  L.push('                _dispatch(abi.encodeCall(this.apply_, (s.action, s.picks)), name);');
  L.push('                if (_diverged) break;');
  L.push('            }');
  L.push('            _assertState(s.post, _project(), name);');
  L.push('            if (_diverged) break;');
  L.push('        }');
  L.push('    }');
  L.push('');
  L.push('    /// A pick the action declares must have been drawn. Absence means the spec');
  L.push('    /// and the config disagree about the action\'s shape, which would otherwise');
  L.push('    /// surface as the driver silently using a zero.');
  L.push(`    function _requirePicks(${model.lib}.Action a, ${model.lib}.Picks memory p) private pure {`);
  const withPicks = model.actions.filter((a) => a.picks.length > 0);
  if (withPicks.length === 0) {
    L.push('        // no action declares a nondet pick');
    L.push('        (a, p);');
  } else {
    withPicks.forEach((a, i) => {
      const kw = i === 0 ? 'if' : '} else if';
      L.push(`        ${i === 0 ? '' : ''}${kw} (a == ${model.lib}.Action.${a.enumName}) {`);
      for (const pick of a.picks) {
        L.push(
          `            require(p.has${cap(pick)}, "${model.name}: action \`${a.name}\` did not draw nondet pick \`${pick}\`");`,
        );
      }
    });
    L.push('        }');
  }
  L.push('    }');
  L.push('');
  L.push('    /// Compare every state variable, accumulating rather than short-circuiting,');
  L.push('    /// so one step reports every field that moved.');
  L.push('    function _assertState(');
  L.push(`        ${model.lib}.State memory model_,`);
  L.push(`        ${model.lib}.State memory chain,`);
  L.push('        string memory action');
  L.push('    ) private {');
  const helpers = new Map();
  for (const s of model.state) {
    L.push(...compareStatements(s.node, `"${s.name}"`, `model_.${s.name}`, `chain.${s.name}`, model, helpers, 8));
  }
  L.push('        _reportIfDiverged(action);');
  L.push('    }');
  for (const body of helpers.values()) {
    L.push('');
    L.push(...body);
  }
  L.push('}');

  // console2 is used inside the loop; import it here rather than relying on the
  // base contract re-exporting it.
  const out = L.join('\n') + '\n';
  return out.replace(
    `import { QuintReplayBase } from "${runtimeImport}/QuintReplayBase.sol";`,
    `import { console2 } from "forge-std/console2.sol";\n\nimport { QuintReplayBase } from "${runtimeImport}/QuintReplayBase.sol";`,
  );
}

/**
 * Statements comparing one value. Structs and arrays delegate to a generated
 * helper (registered in `helpers`) so the emitted code stays readable and a
 * shape used twice is compared by one function.
 */
function compareStatements(node, fieldExpr, m, c, model, helpers, indentCols) {
  const pad = ' '.repeat(indentCols);
  const q = model.qualify;

  if (node.kind === 'struct' || node.kind === 'array') {
    const fn = ensureHelper(node, model, helpers);
    return [`${pad}_mismatches += ${fn}(${fieldExpr}, ${m}, ${c});`];
  }
  return [`${pad}_mismatches += ${scalarCompare(node, fieldExpr, m, c, model)};`];
}

function scalarCompare(node, fieldExpr, m, c, model) {
  switch (node.kind) {
    case 'uint':
      return `_eqU(${fieldExpr}, ${m}, ${c})`;
    case 'int':
      return `_eqI(${fieldExpr}, ${m}, ${c})`;
    case 'bool':
      return `_eqB(${fieldExpr}, ${m}, ${c})`;
    case 'address':
      return `_eqA(${fieldExpr}, ${m}, ${c})`;
    case 'bytes32':
      return `_eqBytes32(${fieldExpr}, ${m}, ${c})`;
    case 'string':
      return `_eqStr(${fieldExpr}, ${m}, ${c})`;
    case 'enum': {
      const fn = `${model.lib}.${lower1(node.decl.name)}Name`;
      return `_eqStr(${fieldExpr}, ${fn}(${m}), ${fn}(${c}))`;
    }
    default:
      throw new Error(`no comparison for type kind "${node.kind}"`);
  }
}

function ensureHelper(node, model, helpers) {
  const q = model.qualify;
  const key = node.kind === 'struct' ? `s:${node.decl.name}` : `a:${q(node.inner)}`;
  const fn =
    node.kind === 'struct' ? `_cmp${node.decl.name}` : `_cmpArr${sanitize(cap(q(node.inner)))}`;
  if (helpers.has(key)) return fn;
  helpers.set(key, []); // reserve, so a self-referential shape cannot recurse forever

  const L = [];
  if (node.kind === 'struct') {
    L.push(`    function ${fn}(`);
    L.push('        string memory f,');
    L.push(`        ${q(node)} memory m,`);
    L.push(`        ${q(node)} memory c`);
    L.push('    ) private returns (uint256 n) {');
    for (const field of node.fields) {
      if (field.node.kind === 'struct' || field.node.kind === 'array') {
        const inner = ensureHelper(field.node, model, helpers);
        L.push(
          `        n += ${inner}(string.concat(f, ".${field.name}"), m.${field.name}, c.${field.name});`,
        );
      } else {
        L.push(
          `        n += ${scalarCompare(field.node, `string.concat(f, ".${field.name}")`, `m.${field.name}`, `c.${field.name}`, model)};`,
        );
      }
    }
    L.push('    }');
  } else {
    L.push(`    function ${fn}(`);
    L.push('        string memory f,');
    L.push(`        ${q(node)} memory m,`);
    L.push(`        ${q(node)} memory c`);
    L.push('    ) private returns (uint256 n) {');
    L.push('        n += _eqU(string.concat(f, ".length"), m.length, c.length);');
    L.push('        // Lengths differing makes element-wise output noise, not signal.');
    L.push('        if (m.length != c.length) return n;');
    L.push('        for (uint256 i = 0; i < m.length; i++) {');
    if (node.inner.kind === 'struct' || node.inner.kind === 'array') {
      const inner = ensureHelper(node.inner, model, helpers);
      L.push(
        '            n += ' + inner + '(string.concat(f, "[", vm.toString(i), "]"), m[i], c[i]);',
      );
    } else {
      L.push(
        `            n += ${scalarCompare(node.inner, 'string.concat(f, "[", vm.toString(i), "]")', 'm[i]', 'c[i]', model)};`,
      );
    }
    L.push('        }');
    L.push('    }');
  }
  helpers.set(key, L);
  return fn;
}

/** `contract <Name>Traces` - one test per committed fixture. */
export function emitTraces(model, cmd, { fixtures, driverImport, driverContract, contractName }) {
  const L = [];
  L.push(HEADER(model, cmd));
  L.push(`import { ${driverContract} } from "${driverImport}";`);
  L.push('');
  L.push(`/// ${fixtures.length} committed trace${fixtures.length === 1 ? '' : 's'} for ${model.specPath}.`);
  L.push('///');
  L.push('/// One test per trace, because Foundry re-runs `setUp` per test function:');
  L.push('/// each trace replays from a fresh deployment, and a failure names the one');
  L.push('/// trace to rerun rather than the whole suite.');
  L.push(`contract ${contractName} is ${driverContract} {`);
  // Multi-line bodies, and a blank line between them: `forge fmt` rewrites the
  // one-line form, and generated output that fails a consumer's format check is
  // a papercut for every consumer.
  fixtures.forEach((f, i) => {
    if (i > 0) L.push('');
    L.push(`    function ${f.testName}() public {`);
    L.push(`        _replay("${f.path}");`);
    L.push('    }');
  });
  L.push('}');
  return L.join('\n') + '\n';
}
